name: Deploy Backend to NHN Cloud

on:
    push:
        branches:
            - main # main 브랜치에 push 될 때마다 실행

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # 1. GitHub 저장소에서 코드 가져오기
            - name: Checkout repository
              uses: actions/checkout@v3

            # 2. Git 저장소를 안전한 디렉토리로 등록
            # 'dubious ownership' 에러를 해결합니다.
            - name: Mark git directory as safe
              run: git config --global --add safe.directory /home/ubuntu/fourmen-backend

            # 3. 프로젝트 디렉토리의 소유권을 현재 실행 중인 사용자에게 부여
            # 'Failed to delete' 권한 문제를 해결합니다.
            - name: Grant permissions to the project directory
              run: sudo chown -R $USER:$USER /home/ubuntu/fourmen-backend

            # 4. NHN Cloud 서버에 SSH 접속해서 배포
            - name: Deploy to NHN Cloud via SSH
              uses: appleboy/ssh-action@v0.1.7
              with:
                  host: ${{ secrets.SERVER_IP }} # GitHub Secrets에서 설정
                  username: ubuntu # NHN Cloud Ubuntu 기본 계정
                  key: ${{ secrets.SSH_KEY }} # pem 키 내용 (Secrets에 저장)
                  script: |
                      # 배포할 프로젝트 경로 (최초 clone은 직접 해둬야 함)
                      cd ~/fourmen-backend

                      # 최신 코드 가져오기
                      git pull origin main

                      # Maven 빌드 (테스트는 건너뛰기)
                      ./mvnw clean package -DskipTests

                      # 기존 실행중인 Spring Boot 종료
                      pkill -f 'java -jar' || true

                      # 새 JAR 실행 (nohup으로 백그라운드 실행)
                      nohup java -jar target/*.jar > app.log 2>&1 &
