name: Deploy Backend to NHN Cloud (Build and Deploy)

on:
  push:
    branches:
      - main # main 브랜치에 push 될 때마다 실행

jobs:
  # ===============================================================
  # 1. Build Job: GitHub 서버에서 소스코드를 빌드하여 .jar 파일을 생성
  # ===============================================================
  build:
    runs-on: ubuntu-latest
    steps:
      # (1-1) GitHub 저장소에서 코드 가져오기
      - name: Checkout repository
        uses: actions/checkout@v3

      # (1-2) JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      # (1-3) (⭐️핵심 해결책) mvnw 파일에 실행 권한 부여
      - name: Grant execute permission to mvnw
        run: chmod +x ./mvnw

      # (1-4) Maven 빌드 실행
      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      # (1-5) 빌드된 .jar 파일을 Artifact로 업로드
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: executable-jar
          path: target/*.jar

  # ===============================================================
  # 2. Deploy Job: 빌드된 .jar 파일을 실제 서버에 배포
  # ===============================================================
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # (2-1) .jar 파일을 다운로드
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: executable-jar

      # (2-2) scp를 사용해 .jar 파일을 NHN Cloud 서버로 복사
      - name: Copy JAR to server via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          source: "*.jar"
          target: "/home/ubuntu/fourmen-backend"

      # (2-3) SSH로 서버에 접속해서 앱을 강제 종료 후 실행
      - name: Deploy to NHN Cloud via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/fourmen-backend

            # 1. 실행중인 jar 파일의 프로세스 ID(PID)를 직접 찾습니다.
            # `grep -v grep`은 grep 명령어 자체는 검색에서 제외하는 역할입니다.
            PID=$(ps -ef | grep 'java -jar' | grep -v grep | awk '{print $2}')

            # 2. PID가 존재한다면(앱이 실행중이라면), kill -9 명령어로 강제 종료시킵니다.
            if [ -n "$PID" ]; then
              echo "Found running process with PID: $PID. Force killing it with kill -9."
              sudo kill -9 $PID
              sleep 5 # OS가 포트를 완전히 해제할 시간을 줍니다.
            else
              echo "No running process found. Skipping kill command."
            fi

            # 3. 새 버전의 앱을 실행합니다.
            echo "Starting new application..."
            setsid java -jar *.jar > app.log 2>&1 &

            # 4. (디버깅) 앱이 정상 실행되었는지 로그를 확인합니다.
            sleep 10 # 앱이 시작될 시간을 충분히 줍니다.
            echo "====== Displaying new app.log to check status ======"
            cat app.log
            echo "====================================================="
