name: Deploy Backend to NHN Cloud

on:
    push:
        branches:
            - main # main 브랜치에 push 될 때마다 실행

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # 1. GitHub 저장소에서 코드 가져오기 (이 단계는 SSH만 사용할 경우 필수는 아님)
            - name: Checkout repository
              uses: actions/checkout@v3

            # 2. NHN Cloud 서버에 SSH 접속해서 배포
            - name: Deploy to NHN Cloud via SSH
              uses: appleboy/ssh-action@v0.1.7
              with:
                  host: ${{ secrets.SERVER_IP }}
                  username: ubuntu
                  key: ${{ secrets.SSH_KEY }}
                  script: |
                      # --- 여기부터 NHN Cloud 서버에서 실행됩니다 ---

                      # 배포할 프로젝트 경로로 이동
                      cd ~/fourmen-backend

                      # (해결책 1) 'dubious ownership' 에러 해결
                      # git pull을 실행하기 전에 이 디렉토리가 안전하다고 설정합니다.
                      git config --global --add safe.directory /home/ubuntu/fourmen-backend

                      # 최신 코드 가져오기
                      git pull origin main

                      # (해결책 2) Maven 빌드
                      # ubuntu 사용자가 직접 빌드를 실행하므로 target 폴더 삭제 권한 문제가 발생하지 않습니다.
                      ./mvnw clean package -DskipTests

                      # 기존 실행중인 Spring Boot 종료
                      pkill -f 'java -jar' || true

                      # 새 JAR 실행 (nohup으로 백그라운드 실행)
                      nohup java -jar target/*.jar > app.log 2>&1 &
